### ISSUE TITLE
[TODO] Menu

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#10]
@GillesLabs-TGV 
- Est-ce que tu peux faire un joli menu en mode start screen, où l'user peut choisir de jouer avec les 4 propositions, sans propositions, etc ? 
- Un bouton mute
- Un bouton pause

**Comment by Rude-Monkey** [comment]
Je peux le faire, mais est-ce qu'on en a l'utilité ?

- Je peux faire un bouton pause. Par contre, vu que mettre en pause pendant un extrait c'est un peu de la triche, je propose que ce soit un switch qui, si activé, va mettre en pause le jeu entre deux extraits. Par contre on a déjà une pause entre deux extraits puisqu'il faut passer la fenêtre qui indique la bonne réponse pour pouvoir continuer.

- Un bouton mute... OK, mais pour faire joli ou il y a un réel intérêt à mettre un bouton mute ? (qui contrairement au bouton pause n'arrêterait pas le jeu mais laisserait continuer l'extrait sans son...

**Comment by Rude-Monkey** [comment]
On a : 

- un menu
- la possibilité d'y choisir si l'on veut avoir des propositions de réponses
- un début de css

Ça arrive : 

- voir les options qui pourraient être ajoutées
- afficher les highscores dans le menu/créer un composant pour les highscores ?
- améliorer le css

**Comment by Rude-Monkey** [comment]
IT'S DONE MATE!
