### ISSUE TITLE
Cross-origin

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#11]
@Taiki-San J'arrive bien a appeler l'api depuis un client REST :) En revanche quand je veux l'appeler depuis la webapp j'ai un soucis de Cross-origin (logique). Donc est-ce que tu pourrais rajouter dans le header de la réponse un truc du genre `"Access-Control-Allow-Origin: *"` ?

**Comment by Taiki-San** [comment]
C'est fait :)

**Comment by CapsHil** [comment]
On s'en approche mais c'est pas encore ca ;)

Tu peux check ca ? 
https://stackoverflow.com/questions/25727306/request-header-field-access-control-allow-headers-is-not-allowed-by-access-contr 
Le soucis vient du back, encore quelques verrous à virer je pense

Pour info ma requête me renvoie : `Failed to load http://localhost:8082/api/test.php?nbSuggestions=0: Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.
`

**Comment by Taiki-San** [comment]
Est-ce que https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/809d0177cf583d3267379f3989ca74b776c90d84 résoudre le problème?

**Comment by CapsHil** [comment]
Nope... J'ai tout ouvert aussi coté client au cas où, mais ca passe pas

**Comment by CapsHil** [comment]
Trouvé ! J'avais pas lu en détail ton commit, mais t'as zappé d'allow les 2 headers du dessus dans ton Access-Control-Allow-Headers ;-P

**Comment by Taiki-San** [comment]
:O
Je savais pas que ça marchais comme ça, GG

**Comment by CapsHil** [comment]
Laisse tomber le cross-origin c'est la loose...
Btw, enfait l'appel à l'API me renvoie bien le JSON, mais avec tout les logs de warning avant, donc le JS kiff pas x) Y'a moyen que tu vires tout ca vite fait ?

PS: Je recois ça concrètement : 
`<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/db.inc.php</b> on line <b>173</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/api/test.php</b> on line <b>51</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/api/test.php</b> on line <b>51</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/api/test.php</b> on line <b>51</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/api/test.php</b> on line <b>51</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api/api/test.php</b> on line <b>51</b><br />
{"status":"success","songID":"2","filename":"music\/extract_2.mp3","suggestions":[{"songID":"2","trackName":"Test","artistName":"Test"}]}`

**Comment by Taiki-San** [comment]
Heu, ouais, mon serveur de test les avais désactivé. Je regarde ça. J'ai aussi fait un commit qui les enlèves dans l'immédiat
