### ISSUE TITLE
VICTOIRE

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#12]
@Taiki-San @Bougainville @GillesLabs-TGV @Aniyanka 

On a un bout en bout qui fonctionne !!!!!!!!
Maintenant reste plus qu'a se coordonner un peu histoire que tout le monde soit d'accord sur ce qu'il doit attendre/envoyer/retourner niveau JSON, rendre tout ça tout beau tout propre, et déjà on aura un truc à rendre qui tient la route.

**Comment by Taiki-San** [comment]
GG à tous \o/
Je suis AFK pour quelques heures. On discuteras du staging des nouvelles chansons après, ok?
