### ISSUE TITLE
[TODO] Adapt tables

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#13]
@Taiki-San Il faudrait adapter les tables pour pouvoir y ajouter un nom de film/série pour le mode "blind-test film/série"

**Comment by Taiki-San** [comment]
On se contente d'un simple flag ou tu souhaites des changements plus significatifs?
Présentement, on a un nom et un "artiste" pour chaque fichier.
On peut mettre le nom de l'épisode/la série dans un champ et mettre le nom de la série/réalisateur dans l'autre.

**Comment by Taiki-San** [comment]
Pour reformuler la question, souhaites-tu plus de deux champs de métadonnées pour les séries ou pas?

**Comment by Taiki-San** [comment]
@CapsHil Du coup?
