### ISSUE TITLE
API on endpoint test.php apparently doesn't default suggestion number to 4 on GET request.

### ISSUE THREAD

**Issue by Rude-Monkey** [CapsHil/Projet_Web_2017_ESIEA#14]
Tout est dans le titre @Taiki-San je n'ai qu'une seule suggestion dans le JSON renvoyé par l'API alors que la requête ne contient pas de paramètre.

Tu confirmes ?

**Comment by Taiki-San** [comment]
Heu, c'est pas normal mais possible si la base est vide...

**Comment by Rude-Monkey** [comment]
@CapsHil tu as combien de morceaux différents en base actuellement ? Je ne suis tombé que sur trois morceaux différents pour le moment en testant : est-ce qu'il y en a plus que 3 ou est-ce que c'est justement ce qui pourrait expliquer l'erreur (du moins en partie) ?

**Comment by Taiki-San** [comment]
En théorie, ça ne devrait pas suffire, je regarde le code.

**Comment by Rude-Monkey** [comment]
Il y a 6 morceaux en base donc à priori suffisamment pour renvoyer quatre suggestions. Je te confirme que je ne reçois pourtant qu'une seule suggestion par requête.

**Comment by Taiki-San** [comment]
Okay, j'ai pas toute la setup Docker pour tester en condition réelle pour l'instant, je test ça demain. C'est pas le bug évident auquel je pensais, donc il va falloir que je regarde de plus près.

**Comment by Taiki-San** [comment]
Fixed in https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/2cc8b4f42a152823e1fa5959c78b0f267929e28a

**Comment by Rude-Monkey** [comment]
Nope. Almost there. The API should default to 4, not 2.

**Comment by Taiki-San** [comment]
(╯°□°）╯︵ ┻━┻
Toutes mes excuses, https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/a0dc9ba7a142a6c943ee3a67d6e542167e06a603 devrait corriger le problème pour de bon.
