### ISSUE TITLE
[!] Need API change on test.php endpoint

### ISSUE THREAD

**Issue by Rude-Monkey** [CapsHil/Projet_Web_2017_ESIEA#15]
@Taiki-San : En plus de l'autre issue (j'ai maintenant 2 propositions au lieu de 4 par défaut), j'ai un autre problème.

- à la base, j'avais pensé récupérer les propositions rangées de manière aléatoire et l'indice de la bonne réponse pour pouvoir faire la vérification côté front. Dans ce cas, je ne faisais que poster le score en fin de partie.

- Je n'ai rien contre le fait de recevoir des suggestions avec des ID de base puis faire la vérification via l'API, mais si j'ai bien compris ta doc, je ne récupère à aucun moment la string correspondant à la bonne réponse : ça m'empêche de montrer à l'utilisateur la bonne réponse en cas d'erreur de sa part.

Du coup ce que je te propose : 

- soit je récupère à un moment ou un autre la string de la bonne réponse et je m'adapte en faisant une requête post à chaque réponse.

- soit au lieu de m'envoyer les ID des morceaux en base tu m'envoies les quatre propositions déjà rangées de manière aléatoire et l'indice de la bonne réponse dans le JSON. Je fais la vérification de la réponse côté front et je t'envoie, au choix, soit un booléen pour t'indiquer la réussite ou non de l'utilisateur, soit le score de l'utilisateur à la question (donc 0 si il a faux), soit je t'envoie le score en fin de partie uniquement.

*NB* :  en l'état, on n'a pas d'utilisateur identifié. Je pensais, si on a le temps, simplement demander à l'utilisateur son nom en fin de partie et afficher un leaderboard simple. (le même fonctionnement que sur une borne d'arcade en soi)

**Comment by Rude-Monkey** [comment]
On s'est débrouillés autrement... dans l'idéal, il y aurait du nettoyage à faire.

**Comment by Taiki-San** [comment]
Désolé, je viens seulement de recevoir la notification...

Les suggestions sont déjà rangés dans un ordre aléatoire.
La string correspondant à la bonne réponse n'est effectivement que disponible parmi les suggestions, je peux la dupliquer dans un autre champ si tu veux.

L'autre idée que tu proposes est faisable, mais ça implique de déplacer pas mal de code existant de la backend vers la frontend. Si on a le temps, par de problème pour moi mais je ne sais pas si c'est prioritaire.

Pour ce qui est du login à la fin, ça pose un problème côté backend, sachant que je dois être state-less. On peut se passer d'un login à condition que le front se charge de toute la gestion du high score. On en avais pas parlé donc j'était parti sans compter sur ça. On peut changer si c'est important.

**Comment by Rude-Monkey** [comment]
T'inquiète, je n'ai remarqué le rangement aléatoire qu'après avoir posté.

- on a fait sans duplication du champ

- on a donc réussi à faire la vérification dans le front

- pour les high-scores, tu veux dire que l'on ne peut pas t'envoyer à la fois un score et une string pour un pseudo ? Le but est de pouvoir au moins le faire sans authentification. Tu peux à priori soit renvoyer les 5 plus gros scores et les pseudos associés, soit tout balancer et on trie dans le front, non ?

**Comment by Taiki-San** [comment]
Je renvois le top N trié, donc ça ira de ce côté.
C'était pas prévu dans l'arch de la BDD (les top scores sont liés à un userID) mais si c'est important, je peux patcher ça et rajouter un POST à `topScores.php`

**Comment by Rude-Monkey** [comment]
L'idée était de ne pas faire de POST sur test à moins de l'utiliser pour envoyer le score en fin de session, accompagné d'un pseudo à stocker en bdd.

Je doute qu'on aille jusqu'à l'inscription/authentification d'utilisateurs et dans l'immédiat, il faudrait pouvoir envoyer score + pseudo. Après, que ce soit sur test.php ou topScores.php, c'est toi qui dis où on doit t'envoyer ça. Au meilleur des cas on aura une authentification fonctionnelle et il suffira de remplacer le pseudo par un cookie ou un UID.

Qu'est-ce que tu en penses ?

**Comment by Taiki-San** [comment]
Le principal problème que j'ai à dissocier le nom du compte est "l'usurpation d'identité" et la gestion de la fusion.
Si on dit fuck au username dans les top scores et dans la chat box, je peux faire complètement sauter la base user. En revanche, si on souhaite garder la base au cas où, je ne sais pas trop comment gérer la création d'un compte avec un nom identique à un nom déjà utilisé. En fonction du comportement, je peux tenter de faire des optimisations chiante à inverser donc l'idéal serait d'être sûr.

**Comment by Rude-Monkey** [comment]
En l'état, la bdd user sera inutilisée. 

- On veut juste pouvoir indiquer un pseudo en fin de partie pour aller avec le score.

- On veut également récupérer les 5 meilleurs scores et le pseudo associé à chacun pour les afficher

Je ne peux pas garantir que la bdd reste inutilisée, mais... highly unlikely.

**Comment by Taiki-San** [comment]
Okay, je refactore ça. Par contre, une question concernant les high-scores. Je fais quoi quand un gus bat son score mais qu'il mis-type son pseudo (typiquement, la casse) ? Je fait comme si de rien n'était et je laisse passer un doublon?

**Comment by Rude-Monkey** [comment]
En un mot : tant pis pour lui. =D

**Comment by Taiki-San** [comment]
Le commit https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/61b10e07c236b5b53a7aedaa7777e680767db2fe implémente tout ça. Par contre, je ne dirais vraiment pas non à un peu de test...

**Comment by Taiki-San** [comment]
Le bordel à l'air stable. L'API a un peu changé pour refléter tout ça. Faites gaffe aux noms d'utilisateurs dans les arguments d'input qui ont été unifiés sous le nom `username`.
