### ISSUE TITLE
SUPER MÉGA URGENT

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#16]
@Taiki-San Il y a un gros soucis énorme et urgent sur le back ! Sometimes, la réponse arrive bien en 200, mais elle est VIDE ! Ceci est très facheux !

PS: J'ai ajouté quelques tracks... On en a 187 maintenant ! \o>

![22883975_10212446755958199_168508495_o](https://user-images.githubusercontent.com/6097579/32122305-2f1c9fce-bb60-11e7-9988-2ab3dd555472.png)

**Comment by Taiki-San** [comment]
Désolé, j'ai cassé des trucs à cause #15, je suis en train de tout patcher ASAP...

**Comment by Taiki-San** [comment]
Le schema de la DB a changé par contre, vérifie que tout est à jour.

**Comment by Taiki-San** [comment]
Tu as un fichier error_log à côté des .php? Je n'arrive pas à reproduire.

**Comment by Rude-Monkey** [comment]
- Perso, je n'ai pas de fichier contenant le nom log hormis api.log qui contient des erreurs qui étaient soulevées quand on essayait d'accéder à des fichiers qui n'existaient pas, je n'ai pas de fichier contenant 'log'.

- Par contre, j'ai aussi ça : 
![screenshot from 2017-10-27 23-56-25](https://user-images.githubusercontent.com/16140019/32126744-92592348-bb72-11e7-815f-331ef592da01.png)

**Comment by Taiki-San** [comment]
C'est le résultat attendu, on est d'accord?

**Comment by Rude-Monkey** [comment]
Ah non... non seulement j'aimerais recevoir une réponse non vide à chaque requête, mais j'aimerais aussi que toutes les propositions soient différentes ^^' (cf. Kill Bill)

**Comment by Taiki-San** [comment]
C'est pas le même songID: c'est un doublon dans la BDD.
Par contre, pour les réponses vides, je ne vois pas à quoi tu fais référence...

**Comment by Rude-Monkey** [comment]
- Je reçois une réponse du serveur (code: 200) mais il n'y a aucun contenu. Regarde à droite dans la console dans le screen qu'a envoyé Raby.

- Si tu testes de ton côté, tu devrais voir dans la console JS une ligne disant que le module './undefined' est introuvable quand ça arrive.

**Comment by Taiki-San** [comment]
J'ai pas tout le bordel Docker en place pour l'instant :|
Par contre, je n'ai pas la moindre idée de ce qui peux poser problème: `GET test.php` me semble à peu près stable et n'a pas de raison de crash sans raison...
Vous pouvez me montrer la requête effectuée?

**Comment by Rude-Monkey** [comment]
Je ne sais pas non plus pourquoi il nous fait ça... est-ce que la bdd aurait du mal à fournir une réponse à temps pour l'API ? Est-ce que c'est l'API qui est mal optimisée ?

Une chose est certaine : on n'avait pas ce problème lorsqu'on n'avait que 6 morceaux en base.

**Comment by Taiki-San** [comment]
La requête prend 79ms sur le screen de Raby, je ne penses pas que ça soit un timeout.
De plus, je limite le nombre de résultats que je demande au strict minimum et les index sont correctement configurés donc trop pas de problème de performance de mon côté.
De plus, le plus gros changement depuis le 6 morceaux dans la BDD est le gros refactoring qui a changé le modèle. J'aurais tendance à le soupçonner mais ça ne suffit à expliquer des réponses vides sans log.

**Comment by Rude-Monkey** [comment]
En tout cas, l'API répond donc le problème vient : 
 - soit de l'API
 - soit de ce qu'il y a derrière (ie: la BDD, même si en effet, je ne vois pas trop comment)

**Comment by Taiki-San** [comment]
Dans tous les cas, j'ai besoin de savoir ce que vous envoyez à l'API quand elle se gauffre pour pouvoir chercher le problème :|...

**Comment by Rude-Monkey** [comment]
- Requête GET sur test.php
- Aucun paramètre

- Un coup ça marche
- Le suivant ça ne marche plus

**Comment by Taiki-San** [comment]
Je reproduit, je regarde ça.

**Comment by Rude-Monkey** [comment]
Et pourtant... 


![sans titre](https://user-images.githubusercontent.com/16140019/32127890-352ac78c-bb7a-11e7-865b-16345a6e188b.png)

[EDIT] OK

**Comment by Taiki-San** [comment]
Le commit https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/aaaef7cc9f64d3203a57ff00038da794a08b2a11 devrait corriger le problème.
Confirmez si c'est bon.

**Comment by Rude-Monkey** [comment]
À mon avis, on s'en approche. La réponse du GET arrive encore souvent vide, mais le OPTIONS juste avant n'est plus vide (cf. screenshot)

![screenshot from 2017-10-28 01-00-45](https://user-images.githubusercontent.com/16140019/32128092-79c2dc80-bb7b-11e7-9021-20247c11f191.png)

**Comment by Taiki-San** [comment]
\o/
C'est le parseur JSON qui se gaufre quand il y a de l'UTF8!
FML.

**Comment by Taiki-San** [comment]
J'ai une erreur `JSON_ERROR_UTF8 : Malformed UTF-8 characters, possibly incorrectly encoded`.
On dirait que le problème sont les données de test qui cassent le parseur JSON, et empêche de sortir quoi que ce soit

**Comment by Rude-Monkey** [comment]
Le problème, c'est qu'il n'y avait pas cette erreur lorsqu'on n'avait que les données de test...

C'est @CapsHil qui a populé la base avec des données fournies par le BDA. Il faut voir si tu peux t'arranger avec lui.

**Comment by Taiki-San** [comment]
Je suis en train de bidouiller le format de la BDD pour être sûr que ça reste de l'UTF8

**Comment by Taiki-San** [comment]
En principe, c'est patché pour de bon.

**Comment by Rude-Monkey** [comment]
Aucune erreur sur 3 séries complètes de 5 questions: I'm closing it !

Merci !
