### ISSUE TITLE
UPDATE test.php

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#20]
@Taiki-San Est-ce que tu pourrais rajouter dans l'appel de "test.php" un params 'genre' histoire de pouvoir selectionner le genre de la track retournée ?

**Comment by Taiki-San** [comment]
Ça devrais faire le job.

**Comment by CapsHil** [comment]
Est-ce que tu penses que c'est possible de mettre plusieurs genre ? Si c'est chiant dis le on fera sans tant pis ;)

**Comment by Taiki-San** [comment]
_I see what you're doing there_
Un peu chiant mais faisable, envoi une array et je me démerde.

**Comment by CapsHil** [comment]
❤️ 🦄

**Comment by Taiki-San** [comment]
Mieux?

**Comment by CapsHil** [comment]
@Taiki-San Tu attends juste un array de genreId [1, 2, ...] ?

**Comment by Taiki-San** [comment]
Ouais. L'argument s'appelle `genre` par contre.

**Comment by CapsHil** [comment]
Ca à l'air de marcher, est-ce que tu pourrais juste modifier la table pour que l'extract filename ne soit pas unique ? Comme ca on peut mettre un extrait pour un film, et une musique "classique"

**Comment by Taiki-San** [comment]
Done.

**Comment by CapsHil** [comment]
En fait ca n'a pas l'air de fonctionner, il ne prend visiblement pas le genre en compte

**Comment by Taiki-San** [comment]
Si tu utilises la base dans le dépôt, il n'y a qu'un seul genre.
Si tu lui demande un genre qui n'existe pas/n'a pas de chanson, il va l'ignorer.

**Comment by CapsHil** [comment]
Non j'en ai rajouté un à la mano avec 6 extract liés à ce genre

**Comment by Taiki-San** [comment]
Il existe dans la BDD de genre?

**Comment by CapsHil** [comment]
Yes

**Comment by Taiki-San** [comment]
Il y avait une petite erreur mais à part ça, ça marche chez moi.

**Comment by CapsHil** [comment]
Ca marche pas chez moi..., tu fais quoi exactement comme requete ?

**Comment by Taiki-San** [comment]
`test.php?input={"genre":[6]}` avec une chanson en BDD pour ce genre et le genre existant dans la table dédiée. Commit tes changements dans le schéma de BDD, histoire que je puisse regarder de plus près.

**Comment by CapsHil** [comment]
Cette requete ne marche pas chez moi :/ Je te commit ca

**Comment by Taiki-San** [comment]
J'ai patché le php localement pour accepter un input dans l'URL, mais une requête REST devrait avoir le même effet...

**Comment by Taiki-San** [comment]
Tu peux avoir le même effet en ouvrant `test.php`et en ajoutant à la dixième ligne (après `$input = json_decode`...) le code suivant:

```
if(!empty($_REQUEST['input']))
{
	$input = json_decode($_REQUEST['input'], true);
}
```

**Comment by CapsHil** [comment]
C'est commit, même résultat en ajoutant ton code

**Comment by Taiki-San** [comment]
Il y avait de petites anomalies dans le fichier SQL... Reessaie?

**Comment by CapsHil** [comment]
Ah oui c'est parce que je les avaient ajoutées à la main après mon import à la mano dans PhpMyAdmin ^^

**Comment by Taiki-San** [comment]
Le fichier patché ne résout pas le problème ?

**Comment by CapsHil** [comment]
Not at all

**Comment by Taiki-San** [comment]
https://github.com/CapsHil/Projet_Web_2017_ESIEA/commit/98692878e879a490f0214388d0ce0b621c8b7eb9 devrait corriger l'issue
