### ISSUE TITLE
[TO FIX] Extracts identiques

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#21]
@Taiki-San  Il y a un gros soucis, quand on choisi le genre '2' (musique), on a TOUJOURS le même résultat (Fame - Irene Cara). Même soucis pour @GillesLabs-TGV et moi

**Comment by Taiki-San** [comment]
Probablement une optimisation de performance (http://jan.kneschke.de/projects/mysql/order-by-rand/ ) qui se gaufre. Essayez avec le dernier commit.

**Comment by CapsHil** [comment]
C'est ok ca marche !
