### ISSUE TITLE
[TO FIX] Top scores

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#22]
@Taiki-San  Je suis entrain d'implem les top scores, et la l'API ne me renvoi rien pour le GET topScores.php ;) J'en ai ajouté 5 ou 6 dans la DB

**Comment by Taiki-San** [comment]
C'est bon?

**Comment by CapsHil** [comment]
Nope :/

**Comment by Taiki-San** [comment]
Et maintenant?

**Comment by CapsHil** [comment]
Yes it's ok !

**Comment by CapsHil** [comment]
Ah en fait il y a un petit soucis, le rank est inversé, genre le plus petit score est premier et le meilleur dernier

**Comment by Taiki-San** [comment]
Arf. Ça devrait résoudre le problème.

**Comment by CapsHil** [comment]
Parfait ! :)
