### ISSUE TITLE
Mail prof && rendu

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#7]
@Taiki-San @Bougainville @GillesLabs-TGV @Aniyanka 

Est-ce que l'un d'entre vous aurait l'adresse mail du prof ? Et quelle est la date précise du rendu ? ^^

**Comment by Taiki-San** [comment]
Tu ne lui avais pas envoyé un mail avec l'adresse du repo?
Pour le rendu, j'ai noté 29/10/2017 à 22h

**Comment by Taiki-San** [comment]
<img width="957" alt="screen shot 2017-10-29 at 21 29 49" src="https://user-images.githubusercontent.com/731787/32147997-594c3cfa-bcf0-11e7-992d-77ee59b4f205.png">

**Comment by Taiki-San** [comment]
<img width="961" alt="screen shot 2017-10-29 at 21 30 57" src="https://user-images.githubusercontent.com/731787/32148004-7c014bdc-bcf0-11e7-8ffd-5a7b0ec3f806.png">
