### ISSUE TITLE
Connect BDD

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#8]
@Bougainville @Taiki-San Je n'arrive pas à me connecter à la BDD. Sachant que le mysql tourne sur un autre container que php. Une idée ?

`{"status":"error","error":"Could not connect to database"}`

**Comment by Taiki-San** [comment]
Si c'est un autre conteneur, il faut peut-être mettre autre chose que localhost dans la ligne de connexion dans `config.inc.php`.

**Comment by CapsHil** [comment]
Of course, j'ai mis l'adresse du container pourtant ca ne fonctionne pas

**Comment by Taiki-San** [comment]
La BDD s'appelle bien `sirius` (avec tous les droits mis, etc etc...)?

**Comment by CapsHil** [comment]
Yep `define('dbName', 'mysql:host=mysql;dbname=sirius');`

Sachant que `mysql` est l'adresse du container mysql

**Comment by Taiki-San** [comment]
J'ai mis à jour `utils.inc.php`. Il devrait créer un fichier backend.log avec le message d'erreur

**Comment by CapsHil** [comment]
Je l'avais déjà fait chez moi ;)

**Comment by Taiki-San** [comment]
Le message n'aide pas?

**Comment by Taiki-San** [comment]
Si tu peux le c/c, ça serait cool. Sans, je ne sais pas trop quoi chercher :|

**Comment by CapsHil** [comment]
`Error : could not find driver`

**Comment by Taiki-San** [comment]
Okay, il manque le driver MySQL/PDO dans l'installation de PHP. Je ne sais pas sur quelle distribution Docker tourne mais si Debian/Ubuntu, on dirait que la solution est là https://stackoverflow.com/questions/13375061/installing-pdo-driver-on-mysql-linux-server

**Comment by CapsHil** [comment]
Effectivement j'ai installé le driver PDO (relou avec docker !), maintenant j'ai `Error : SQLSTATE[HY000] [2002] No such file or directory`, je cherche depuis un moment et j'ai rien trouvé qui fonctionne pour l'instant

**Comment by Taiki-San** [comment]
Okay. Sais-tu si il y a une blague avec les ports? En regardant https://github.com/akeneo/transporteo/issues/62, on dirait que l'erreur apparait quand la `dbName` est incorrect/incomplet.

**Comment by CapsHil** [comment]
Bah écoute j'ai laissé le port par défaut (3306) donc en théorie y'a pas de raisons pour que ca fasse *****

**Comment by Taiki-San** [comment]
PHP et MySQL, la voilà ta raison pour que ça fasse de la **** :|
Le serveur MySQL accepte les connexions remote?

**Comment by CapsHil** [comment]
TROUVÉ !!! Va savoir pourquoi, même avec le port par défaut il faut le préciser dans le config.inc.php...

**Comment by Taiki-San** [comment]
PHP ¯\\\_(ツ)\_/¯
GG en tout cas !
