### ISSUE TITLE
Add song

### ISSUE THREAD

**Issue by CapsHil** [CapsHil/Projet_Web_2017_ESIEA#9]
@Taiki-San Tu peux me dire vite fait ou je dois mettre les .mp3 exactement ? Flemme de lire du PHP ;-P

**Comment by Taiki-San** [comment]
Où tu veux tant que le config.inc.php est à jour. Pour l'instant, je pensais que le chemin ressemblerai à celui de la repo GitHub (code de la backend dans `~/backend/api/` et la musique dans `~/music/`). Pour ce qui est de l'upload des fichiers, je ne sais pas trop où est le repertoire de staging pour l'instant, ça va dépendre du front.

**Comment by CapsHil** [comment]
Pour l'instant je veux pas upload depuis le front, juste ajouter à la mano dans mysql, et tenter de faire un GET depuis le front pour tester si ca marche ;)

**Comment by Taiki-San** [comment]
Okay, l'entrée dans la BDD devrait être le nom du fichier dans `music` (donc pour `~/music/song.mp3`, l'entrée en BDD est `song.mp3`). Je renvois ensuite `$publicMusicDirectory . $nom` à travers l'API.

**Comment by CapsHil** [comment]
Okey !
T'as testé tes méthodes ? Parce que pour [GET]test.php il me retourne `{"status":"error","error":"could not generate a song"}` alors que j'ai 2 files sur mysql (et dans music of course)

**Comment by Taiki-San** [comment]
C'est la seule qu'on avait pas testé, je regarde ça tout de suite.

**Comment by Taiki-San** [comment]
J'ai trouvé le bug, il suffit de remplacer la ligne 115 de db.inc.php par ``$req = $bdd->prepare('SELECT r1.`ID` ``. Il y a un autre problème sur lequel je suis en train de travailler. Limite le nombre de suggestion au nombre de chanson dans la BDD pour l'instant.

**Comment by CapsHil** [comment]
Oui je l'avais déjà limité à 0 comme ca au moins... ;P Merci ! Je viens de push la ou j'en suis du coup, avec 2 .mp3 pour tester (caca je sais mais ils sont pas bien gros)

**Comment by Taiki-San** [comment]
Tant que la repo ne se fait pas strike avant le rendu, pas de problème avec moi :P

**Comment by Taiki-San** [comment]
Les deux patchs sont pushed dans dev

**Comment by CapsHil** [comment]
T'emmerde pas, push sur master à partir de maintenant, on a plus le temps de faire des PR ;) Je merge celui que tu viens de faire

**Comment by Taiki-San** [comment]
On peux push sur master maintenant? :o

**Comment by CapsHil** [comment]
Oui je l'ai unlock ;)

**Comment by Taiki-San** [comment]
\o/
